# Release assets are generated by GoReleaser from the defradb repo; bump the
# version and sha256 here when a new versioned release is published.
cask "defradb" do
  version "1.1.0"
  sha256 "860602ba40ffb2205e47e805de73cb3c595434fba9415de5f654aaea3fec75e8"

  url "https://github.com/sourcenetwork/defradb/releases/download/v#{version}/defradb_#{version}_darwin_arm64"
  name "defradb"
  desc "User-centric database prioritizing data ownership, privacy, and security"
  homepage "https://github.com/sourcenetwork/defradb"

  depends_on arch: :arm64

  binary "defradb_#{version}_darwin_arm64", target: "defradb"

  # The binary is not yet signed/notarized, so Gatekeeper quarantines it and
  # macOS reports it as damaged. Strip the quarantine attribute on install;
  # remove this once releases are notarized.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/defradb_#{version}_darwin_arm64"]
    end
  end
end
